_wandb:
    value:
        cli_version: 0.21.0
        e:
            d706du47nkctjapecudoa5b9w0lc0z1y:
                codePath: train_yolo_wandb.py
                codePathLocal: train_yolo_wandb.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1023399686144"
                        used: "453043429376"
                email: sashalarionov2222@mail.ru
                executable: C:\Users\Alex\anaconda3\envs\fd_env\python.exe
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-f150311e-44e1-b7b6-f160-b78713807df4
                host: DESKTOP-C5SVDOM
                memory:
                    total: "16369422336"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\Alex\PycharmProjects\dish_detect\train_yolo_wandb.py
                python: CPython 3.9.23
                root: C:\Users\Alex\PycharmProjects\dish_detect
                startedAt: "2025-07-05T12:39:02.859501Z"
                writerId: d706du47nkctjapecudoa5b9w0lc0z1y
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
                - 80
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.23
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 4
epochs:
    value: 3
img_size:
    value: 640
lr0:
    value: 0.01
model:
    value: yolo11n.pt
optimizer:
    value: auto
