_wandb:
    value:
        cli_version: 0.21.0
        e:
            wkw742gekfn57tw2x45jb8ie4fskb9c8:
                codePath: train_yolo_wandb.py
                codePathLocal: train_yolo_wandb.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1023399686144"
                        used: "451586154496"
                email: sashalarionov2222@mail.ru
                executable: C:\Users\Alex\anaconda3\envs\fd_env\python.exe
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-f150311e-44e1-b7b6-f160-b78713807df4
                host: DESKTOP-C5SVDOM
                memory:
                    total: "16369422336"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\Alex\PycharmProjects\dish_detect\train_yolo_wandb.py
                python: CPython 3.9.23
                root: C:\Users\Alex\PycharmProjects\dish_detect
                startedAt: "2025-07-05T11:48:22.179187Z"
                writerId: wkw742gekfn57tw2x45jb8ie4fskb9c8
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 24
            "4": 3.9.23
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
auto_augment:
    value: randaugment
batch_size:
    value: 16
box_loss_gain:
    value: 7.5
close_mosaic:
    value: 10
cls_loss_gain:
    value: 0.5
copy_paste:
    value: 0
cos_lr:
    value: false
crop_fraction:
    value: 1
dfl_loss_gain:
    value: 1.5
dropout:
    value: 0
epochs:
    value: 2
erasing:
    value: 0.4
img_size:
    value: 640
learning_rate:
    value: 0.01
lr_final:
    value: 0.01
momentum:
    value: 0.937
multi_scale:
    value: true
optimizer:
    value: SGD
warmup_bias_lr:
    value: 0.1
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
